### ISSUE TITLE
create web-scraped API

### ISSUE THREAD

**Issue by pbgnz** [pbgnz/dota-counter-picker#11]
**Project Goal:**
Right now the [data](https://github.com/pbgnz/dota-counter-picker/tree/master/db) of the app is static (done manually)
 
To make the data dynamic, we can build multiple scrapers that grab data from different websites ( dotabuff, gamepedia, etc) and have a cron job set to run those scrappers ever week or so. That way the data will always be up to date.
 
Then we can build a really nice API that will use all the data from the scrapers and we could try to use machine learning to make predictions.
 
**This task:**
A web scraping API needs to be built similar to [this guide](https://stackabuse.com/build-a-web-scraped-api-with-express-and-cheerio/)

**Comment by suleka96** [comment]
Hi, i'd love to give this a try. what are the websites that needs to be scraped?

**Comment by pbgnz** [comment]
**First website**
All the heroes: https://dota2.gamepedia.com/Heroes
For each hero go to their counter page: example https://dota2.gamepedia.com/Abaddon/Counters
and the scraped data could look something like this:
```json
{
  "hero": "abaddon",
  "bad_against": ["ancient_apparition","anti-mage",...],
  "good_against": ["death_prophet","mirana",...]
}
```

**Second website**
This website is the hardest to scrape
All the heroes: https://www.dotabuff.com/heroes
For each hero go to their counter page: example https://www.dotabuff.com/heroes/abaddon/counters?date=week
and the scraped data could look something like this:
```json
[
   {
      "hero":"abaddon",
      "win_rate":"52.90",
      "bad_against":[
         "anti-mage",
         "undying",
         "etc"
      ],
      "good_against":[
         "chen",
         "underloard",
         "etc"
      ],
   },
   {
      "hero":"alchemist",
            "win_rate":"51.00",
      "bad_against":[
         "bloodseeker",
         "monkey_king",
         "etc"
      ],
      "good_against":[
         "spectre",
         "zeus",
         "etc"
      ],
   },
   ...
]

```
